// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VetFlow.Infrastructure.Persistence;

#nullable disable

namespace VetFlow.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(VetFlowDbContext))]
    [Migration("20260731123845_SalesInvoiceSearchText")]
    partial class SalesInvoiceSearchText
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VetFlow.Domain.Catalog.Manufacturer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("SearchText")
                        .IsRequired()
                        .HasMaxLength(700)
                        .HasColumnType("character varying(700)")
                        .HasColumnName("search_text");

                    b.HasKey("Id")
                        .HasName("pk_manufacturers");

                    b.HasIndex("SearchText")
                        .HasDatabaseName("ix_manufacturers_search_text");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchText"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("SearchText"), new[] { "gin_trgm_ops" });

                    b.HasIndex(new[] { "SearchText" }, "ix_manufacturers_name_unique")
                        .IsUnique()
                        .HasDatabaseName("ix_manufacturers_name_unique");

                    b.ToTable("manufacturers");
                });

            modelBuilder.Entity("VetFlow.Domain.Catalog.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ArabicName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("arabic_name");

                    b.Property<string>("ArabicNameNormalized")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("arabic_name_normalized");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<string>("Concentration")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("concentration");

                    b.Property<Guid>("DefaultPurchaseUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("default_purchase_unit_id");

                    b.Property<Guid>("DefaultSaleUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("default_sale_unit_id");

                    b.Property<string>("EnglishName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("english_name");

                    b.Property<bool>("HasExpiration")
                        .HasColumnType("boolean")
                        .HasColumnName("has_expiration");

                    b.Property<bool>("HasOpenExpiration")
                        .HasColumnType("boolean")
                        .HasColumnName("has_open_expiration");

                    b.Property<string>("InternalCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("internal_code");

                    b.Property<string>("InternalNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("internal_notes");

                    b.Property<bool>("IsRefrigerated")
                        .HasColumnType("boolean")
                        .HasColumnName("is_refrigerated");

                    b.Property<bool>("IsSplittable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_splittable");

                    b.Property<Guid>("ManufacturerId")
                        .HasColumnType("uuid")
                        .HasColumnName("manufacturer_id");

                    b.Property<Guid>("NatureId")
                        .HasColumnType("uuid")
                        .HasColumnName("nature_id");

                    b.Property<TimeSpan?>("OpenExpirationPeriod")
                        .HasColumnType("interval")
                        .HasColumnName("open_expiration_period");

                    b.Property<string>("SearchText")
                        .IsRequired()
                        .HasMaxLength(700)
                        .HasColumnType("character varying(700)")
                        .HasColumnName("search_text");

                    b.Property<string>("Size")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("size");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("StorageUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("storage_unit_id");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("ArabicNameNormalized")
                        .HasDatabaseName("ix_products_arabic_name_normalized");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("ArabicNameNormalized"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("ArabicNameNormalized"), new[] { "gin_trgm_ops" });

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_products_category_id");

                    b.HasIndex("DefaultPurchaseUnitId")
                        .HasDatabaseName("ix_products_default_purchase_unit_id");

                    b.HasIndex("DefaultSaleUnitId")
                        .HasDatabaseName("ix_products_default_sale_unit_id");

                    b.HasIndex("InternalCode")
                        .IsUnique()
                        .HasDatabaseName("ix_products_internal_code");

                    b.HasIndex("ManufacturerId")
                        .HasDatabaseName("ix_products_manufacturer_id");

                    b.HasIndex("NatureId")
                        .HasDatabaseName("ix_products_nature_id");

                    b.HasIndex("SearchText")
                        .HasDatabaseName("ix_products_search_text");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchText"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("SearchText"), new[] { "gin_trgm_ops" });

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_products_status");

                    b.HasIndex("StorageUnitId")
                        .HasDatabaseName("ix_products_storage_unit_id");

                    b.ToTable("products");
                });

            modelBuilder.Entity("VetFlow.Domain.Catalog.ProductNature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("SearchText")
                        .IsRequired()
                        .HasMaxLength(700)
                        .HasColumnType("character varying(700)")
                        .HasColumnName("search_text");

                    b.HasKey("Id")
                        .HasName("pk_product_natures");

                    b.HasIndex("SearchText")
                        .HasDatabaseName("ix_product_natures_search_text");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchText"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("SearchText"), new[] { "gin_trgm_ops" });

                    b.ToTable("product_natures");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1000000-0000-4000-8000-000000000001"),
                            Name = "دواء",
                            SearchText = "دواء"
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-4000-8000-000000000002"),
                            Name = "غذاء",
                            SearchText = "غذاء"
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-4000-8000-000000000003"),
                            Name = "مستلزم طبي",
                            SearchText = "مستلزم طبي"
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-4000-8000-000000000004"),
                            Name = "مستلزم حيوانات",
                            SearchText = "مستلزم حيوانات"
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-4000-8000-000000000005"),
                            Name = "منتج عناية",
                            SearchText = "منتج عنايه"
                        });
                });

            modelBuilder.Entity("VetFlow.Domain.Catalog.ProductUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Barcode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("barcode");

                    b.Property<bool>("IsPurchaseUnit")
                        .HasColumnType("boolean")
                        .HasColumnName("is_purchase_unit");

                    b.Property<bool>("IsSaleUnit")
                        .HasColumnType("boolean")
                        .HasColumnName("is_sale_unit");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<decimal?>("QuantityInNextUnit")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("quantity_in_next_unit");

                    b.Property<decimal?>("SellingPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("selling_price");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.HasKey("Id")
                        .HasName("pk_product_units");

                    b.HasIndex("Barcode")
                        .HasDatabaseName("ix_product_units_barcode");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_product_units_product_id");

                    b.HasIndex("UnitId")
                        .HasDatabaseName("ix_product_units_unit_id");

                    b.ToTable("product_units");
                });

            modelBuilder.Entity("VetFlow.Domain.Catalog.Unit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_units");

                    b.ToTable("units");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1000000-0000-4000-8000-000000000001"),
                            Name = "قطعة"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-4000-8000-000000000002"),
                            Name = "علبة"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-4000-8000-000000000003"),
                            Name = "كرتونة"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-4000-8000-000000000004"),
                            Name = "شريط"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-4000-8000-000000000005"),
                            Name = "قرص"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-4000-8000-000000000006"),
                            Name = "زجاجة"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-4000-8000-000000000007"),
                            Name = "سم"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-4000-8000-000000000008"),
                            Name = "مل"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-4000-8000-000000000009"),
                            Name = "لتر"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-4000-8000-000000000010"),
                            Name = "جرام"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-4000-8000-000000000011"),
                            Name = "كيلوجرام"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-4000-8000-000000000012"),
                            Name = "شيكارة"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-4000-8000-000000000013"),
                            Name = "متر"
                        });
                });

            modelBuilder.Entity("VetFlow.Domain.Categories.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("SearchText")
                        .IsRequired()
                        .HasMaxLength(700)
                        .HasColumnType("character varying(700)")
                        .HasColumnName("search_text");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("SearchText")
                        .HasDatabaseName("ix_categories_search_text");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchText"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("SearchText"), new[] { "gin_trgm_ops" });

                    b.HasIndex(new[] { "SearchText" }, "ix_categories_name_unique")
                        .IsUnique()
                        .HasDatabaseName("ix_categories_name_unique");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("VetFlow.Domain.Inventory.InventoryBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date")
                        .HasColumnName("expiry_date");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<Guid>("PurchaseLineId")
                        .HasColumnType("uuid")
                        .HasColumnName("purchase_line_id");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("quantity");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<decimal>("RemainingQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("remaining_quantity");

                    b.Property<decimal>("UnitCostSnapshot")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("unit_cost_snapshot");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_inventory_batches");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_inventory_batches_product_id");

                    b.HasIndex("PurchaseLineId")
                        .HasDatabaseName("ix_inventory_batches_purchase_line_id");

                    b.ToTable("inventory_batches");
                });

            modelBuilder.Entity("VetFlow.Domain.Inventory.InventoryMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActorName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("actor_name");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("quantity");

                    b.Property<int?>("Reason")
                        .HasColumnType("integer")
                        .HasColumnName("reason");

                    b.Property<string>("ReasonNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason_note");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("reference_id");

                    b.Property<int>("Source")
                        .HasColumnType("integer")
                        .HasColumnName("source");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_inventory_movements");

                    b.HasIndex("BatchId")
                        .HasDatabaseName("ix_inventory_movements_batch_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_inventory_movements_product_id");

                    b.HasIndex("ReferenceId")
                        .HasDatabaseName("ix_inventory_movements_reference_id");

                    b.HasIndex("OccurredAt", "Id")
                        .HasDatabaseName("ix_inventory_movements_occurred_at_id");

                    b.ToTable("inventory_movements");
                });

            modelBuilder.Entity("VetFlow.Domain.Inventory.ProductOnHand", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<decimal>("OnHandQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("on_hand_quantity");

                    b.HasKey("ProductId")
                        .HasName("pk_product_on_hands");

                    b.ToTable("product_on_hands");
                });

            modelBuilder.Entity("VetFlow.Domain.Purchasing.PurchaseInvoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("InvoiceDate")
                        .HasColumnType("date")
                        .HasColumnName("invoice_date");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("number");

                    b.Property<string>("SearchText")
                        .IsRequired()
                        .HasMaxLength(700)
                        .HasColumnType("character varying(700)")
                        .HasColumnName("search_text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("SupplierInvoiceReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("supplier_invoice_reference");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("supplier_name");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_amount");

                    b.HasKey("Id")
                        .HasName("pk_purchase_invoices");

                    b.HasIndex("InvoiceDate")
                        .HasDatabaseName("ix_purchase_invoices_invoice_date");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("ix_purchase_invoices_number");

                    b.HasIndex("SearchText")
                        .HasDatabaseName("ix_purchase_invoices_search_text");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchText"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("SearchText"), new[] { "gin_trgm_ops" });

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_purchase_invoices_status");

                    b.ToTable("purchase_invoices");
                });

            modelBuilder.Entity("VetFlow.Domain.Purchasing.PurchaseLineItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<decimal>("LineTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("line_total");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("product_name");

                    b.Property<Guid>("PurchaseInvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("purchase_invoice_id");

                    b.Property<Guid>("PurchaseUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("purchase_unit_id");

                    b.Property<string>("PurchaseUnitName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("purchase_unit_name");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("quantity");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("pk_purchase_line_items");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_purchase_line_items_product_id");

                    b.HasIndex("PurchaseInvoiceId")
                        .HasDatabaseName("ix_purchase_line_items_purchase_invoice_id");

                    b.ToTable("purchase_line_items");
                });

            modelBuilder.Entity("VetFlow.Domain.Purchasing.PurchaseReturn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("number");

                    b.Property<Guid>("PurchaseInvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("purchase_invoice_id");

                    b.Property<DateOnly>("ReturnDate")
                        .HasColumnType("date")
                        .HasColumnName("return_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("SupplierName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("supplier_name");

                    b.HasKey("Id")
                        .HasName("pk_purchase_returns");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("ix_purchase_returns_number");

                    b.HasIndex("PurchaseInvoiceId")
                        .HasDatabaseName("ix_purchase_returns_purchase_invoice_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_purchase_returns_status");

                    b.ToTable("purchase_returns");
                });

            modelBuilder.Entity("VetFlow.Domain.Purchasing.PurchaseReturnLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("product_name");

                    b.Property<Guid>("PurchaseLineItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("purchase_line_item_id");

                    b.Property<Guid>("PurchaseReturnId")
                        .HasColumnType("uuid")
                        .HasColumnName("purchase_return_id");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("quantity");

                    b.HasKey("Id")
                        .HasName("pk_purchase_return_lines");

                    b.HasIndex("BatchId")
                        .HasDatabaseName("ix_purchase_return_lines_batch_id");

                    b.HasIndex("PurchaseLineItemId")
                        .HasDatabaseName("ix_purchase_return_lines_purchase_line_item_id");

                    b.HasIndex("PurchaseReturnId")
                        .HasDatabaseName("ix_purchase_return_lines_purchase_return_id");

                    b.ToTable("purchase_return_lines");
                });

            modelBuilder.Entity("VetFlow.Domain.Sales.SalesInvoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("customer_name");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("number");

                    b.Property<DateOnly>("SaleDate")
                        .HasColumnType("date")
                        .HasColumnName("sale_date");

                    b.Property<string>("SearchText")
                        .IsRequired()
                        .HasMaxLength(700)
                        .HasColumnType("character varying(700)")
                        .HasColumnName("search_text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_amount");

                    b.HasKey("Id")
                        .HasName("pk_sales_invoices");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("ix_sales_invoices_number");

                    b.HasIndex("SaleDate")
                        .HasDatabaseName("ix_sales_invoices_sale_date");

                    b.HasIndex("SearchText")
                        .HasDatabaseName("ix_sales_invoices_search_text");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchText"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("SearchText"), new[] { "gin_trgm_ops" });

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_sales_invoices_status");

                    b.ToTable("sales_invoices");
                });

            modelBuilder.Entity("VetFlow.Domain.Sales.SalesLineItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<decimal>("LineTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("line_total");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("product_name");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("quantity");

                    b.Property<Guid>("SaleUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("sale_unit_id");

                    b.Property<string>("SaleUnitName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sale_unit_name");

                    b.Property<Guid>("SalesInvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("sales_invoice_id");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("pk_sales_line_items");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_sales_line_items_product_id");

                    b.HasIndex("SalesInvoiceId")
                        .HasDatabaseName("ix_sales_line_items_sales_invoice_id");

                    b.ToTable("sales_line_items");
                });

            modelBuilder.Entity("VetFlow.Domain.Sales.SalesReturn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("customer_name");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("number");

                    b.Property<DateOnly>("ReturnDate")
                        .HasColumnType("date")
                        .HasColumnName("return_date");

                    b.Property<Guid>("SalesInvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("sales_invoice_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_sales_returns");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("ix_sales_returns_number");

                    b.HasIndex("SalesInvoiceId")
                        .HasDatabaseName("ix_sales_returns_sales_invoice_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_sales_returns_status");

                    b.ToTable("sales_returns");
                });

            modelBuilder.Entity("VetFlow.Domain.Sales.SalesReturnLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("product_name");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("quantity");

                    b.Property<Guid>("SalesLineItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("sales_line_item_id");

                    b.Property<Guid>("SalesReturnId")
                        .HasColumnType("uuid")
                        .HasColumnName("sales_return_id");

                    b.HasKey("Id")
                        .HasName("pk_sales_return_lines");

                    b.HasIndex("SalesLineItemId")
                        .HasDatabaseName("ix_sales_return_lines_sales_line_item_id");

                    b.HasIndex("SalesReturnId")
                        .HasDatabaseName("ix_sales_return_lines_sales_return_id");

                    b.ToTable("sales_return_lines");
                });

            modelBuilder.Entity("VetFlow.Domain.Catalog.Product", b =>
                {
                    b.HasOne("VetFlow.Domain.Categories.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_products_categories_category_id");

                    b.HasOne("VetFlow.Domain.Catalog.Unit", null)
                        .WithMany()
                        .HasForeignKey("DefaultPurchaseUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_products_units_default_purchase_unit_id");

                    b.HasOne("VetFlow.Domain.Catalog.Unit", null)
                        .WithMany()
                        .HasForeignKey("DefaultSaleUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_products_units_default_sale_unit_id");

                    b.HasOne("VetFlow.Domain.Catalog.Manufacturer", null)
                        .WithMany()
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_products_manufacturers_manufacturer_id");

                    b.HasOne("VetFlow.Domain.Catalog.ProductNature", null)
                        .WithMany()
                        .HasForeignKey("NatureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_products_product_natures_nature_id");

                    b.HasOne("VetFlow.Domain.Catalog.Unit", null)
                        .WithMany()
                        .HasForeignKey("StorageUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_products_units_storage_unit_id");
                });

            modelBuilder.Entity("VetFlow.Domain.Catalog.ProductUnit", b =>
                {
                    b.HasOne("VetFlow.Domain.Catalog.Product", null)
                        .WithMany("Units")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_units_products_product_id");

                    b.HasOne("VetFlow.Domain.Catalog.Unit", null)
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_product_units_units_unit_id");
                });

            modelBuilder.Entity("VetFlow.Domain.Purchasing.PurchaseLineItem", b =>
                {
                    b.HasOne("VetFlow.Domain.Purchasing.PurchaseInvoice", null)
                        .WithMany("Lines")
                        .HasForeignKey("PurchaseInvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_purchase_line_items_purchase_invoices_purchase_invoice_id");
                });

            modelBuilder.Entity("VetFlow.Domain.Purchasing.PurchaseReturnLine", b =>
                {
                    b.HasOne("VetFlow.Domain.Purchasing.PurchaseReturn", null)
                        .WithMany("Lines")
                        .HasForeignKey("PurchaseReturnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_purchase_return_lines_purchase_returns_purchase_return_id");
                });

            modelBuilder.Entity("VetFlow.Domain.Sales.SalesLineItem", b =>
                {
                    b.HasOne("VetFlow.Domain.Sales.SalesInvoice", null)
                        .WithMany("Lines")
                        .HasForeignKey("SalesInvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sales_line_items_sales_invoices_sales_invoice_id");
                });

            modelBuilder.Entity("VetFlow.Domain.Sales.SalesReturnLine", b =>
                {
                    b.HasOne("VetFlow.Domain.Sales.SalesReturn", null)
                        .WithMany("Lines")
                        .HasForeignKey("SalesReturnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sales_return_lines_sales_returns_sales_return_id");
                });

            modelBuilder.Entity("VetFlow.Domain.Catalog.Product", b =>
                {
                    b.Navigation("Units");
                });

            modelBuilder.Entity("VetFlow.Domain.Purchasing.PurchaseInvoice", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("VetFlow.Domain.Purchasing.PurchaseReturn", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("VetFlow.Domain.Sales.SalesInvoice", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("VetFlow.Domain.Sales.SalesReturn", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
