// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VetFlow.Infrastructure.Persistence;

#nullable disable

namespace VetFlow.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(VetFlowDbContext))]
    partial class VetFlowDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VetFlow.Domain.Catalog.Manufacturer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("SearchText")
                        .IsRequired()
                        .HasMaxLength(700)
                        .HasColumnType("character varying(700)")
                        .HasColumnName("search_text");

                    b.HasKey("Id")
                        .HasName("pk_manufacturers");

                    b.HasIndex("SearchText")
                        .HasDatabaseName("ix_manufacturers_search_text");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchText"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("SearchText"), new[] { "gin_trgm_ops" });

                    b.HasIndex(new[] { "SearchText" }, "ix_manufacturers_name_unique")
                        .IsUnique()
                        .HasDatabaseName("ix_manufacturers_name_unique");

                    b.ToTable("manufacturers");
                });

            modelBuilder.Entity("VetFlow.Domain.Catalog.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ArabicName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("arabic_name");

                    b.Property<string>("ArabicNameNormalized")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("arabic_name_normalized");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<string>("Concentration")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("concentration");

                    b.Property<Guid>("DefaultPurchaseUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("default_purchase_unit_id");

                    b.Property<Guid>("DefaultSaleUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("default_sale_unit_id");

                    b.Property<string>("EnglishName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("english_name");

                    b.Property<bool>("HasExpiration")
                        .HasColumnType("boolean")
                        .HasColumnName("has_expiration");

                    b.Property<bool>("HasOpenExpiration")
                        .HasColumnType("boolean")
                        .HasColumnName("has_open_expiration");

                    b.Property<string>("InternalCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("internal_code");

                    b.Property<string>("InternalNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("internal_notes");

                    b.Property<bool>("IsRefrigerated")
                        .HasColumnType("boolean")
                        .HasColumnName("is_refrigerated");

                    b.Property<bool>("IsSplittable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_splittable");

                    b.Property<Guid>("ManufacturerId")
                        .HasColumnType("uuid")
                        .HasColumnName("manufacturer_id");

                    b.Property<Guid>("NatureId")
                        .HasColumnType("uuid")
                        .HasColumnName("nature_id");

                    b.Property<TimeSpan?>("OpenExpirationPeriod")
                        .HasColumnType("interval")
                        .HasColumnName("open_expiration_period");

                    b.Property<string>("SearchText")
                        .IsRequired()
                        .HasMaxLength(700)
                        .HasColumnType("character varying(700)")
                        .HasColumnName("search_text");

                    b.Property<string>("Size")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("size");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("StorageUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("storage_unit_id");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("ArabicNameNormalized")
                        .HasDatabaseName("ix_products_arabic_name_normalized");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("ArabicNameNormalized"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("ArabicNameNormalized"), new[] { "gin_trgm_ops" });

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_products_category_id");

                    b.HasIndex("DefaultPurchaseUnitId")
                        .HasDatabaseName("ix_products_default_purchase_unit_id");

                    b.HasIndex("DefaultSaleUnitId")
                        .HasDatabaseName("ix_products_default_sale_unit_id");

                    b.HasIndex("InternalCode")
                        .IsUnique()
                        .HasDatabaseName("ix_products_internal_code");

                    b.HasIndex("ManufacturerId")
                        .HasDatabaseName("ix_products_manufacturer_id");

                    b.HasIndex("NatureId")
                        .HasDatabaseName("ix_products_nature_id");

                    b.HasIndex("SearchText")
                        .HasDatabaseName("ix_products_search_text");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchText"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("SearchText"), new[] { "gin_trgm_ops" });

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_products_status");

                    b.HasIndex("StorageUnitId")
                        .HasDatabaseName("ix_products_storage_unit_id");

                    b.ToTable("products");
                });

            modelBuilder.Entity("VetFlow.Domain.Catalog.ProductNature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("SearchText")
                        .IsRequired()
                        .HasMaxLength(700)
                        .HasColumnType("character varying(700)")
                        .HasColumnName("search_text");

                    b.HasKey("Id")
                        .HasName("pk_product_natures");

                    b.HasIndex("SearchText")
                        .HasDatabaseName("ix_product_natures_search_text");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchText"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("SearchText"), new[] { "gin_trgm_ops" });

                    b.ToTable("product_natures");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1000000-0000-4000-8000-000000000001"),
                            Name = "دواء",
                            SearchText = "دواء"
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-4000-8000-000000000002"),
                            Name = "غذاء",
                            SearchText = "غذاء"
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-4000-8000-000000000003"),
                            Name = "مستلزم طبي",
                            SearchText = "مستلزم طبي"
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-4000-8000-000000000004"),
                            Name = "مستلزم حيوانات",
                            SearchText = "مستلزم حيوانات"
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-4000-8000-000000000005"),
                            Name = "منتج عناية",
                            SearchText = "منتج عنايه"
                        });
                });

            modelBuilder.Entity("VetFlow.Domain.Catalog.ProductUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Barcode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("barcode");

                    b.Property<bool>("IsPurchaseUnit")
                        .HasColumnType("boolean")
                        .HasColumnName("is_purchase_unit");

                    b.Property<bool>("IsSaleUnit")
                        .HasColumnType("boolean")
                        .HasColumnName("is_sale_unit");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<decimal?>("QuantityInNextUnit")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("quantity_in_next_unit");

                    b.Property<decimal?>("SellingPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("selling_price");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.HasKey("Id")
                        .HasName("pk_product_units");

                    b.HasIndex("Barcode")
                        .HasDatabaseName("ix_product_units_barcode");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_product_units_product_id");

                    b.HasIndex("UnitId")
                        .HasDatabaseName("ix_product_units_unit_id");

                    b.ToTable("product_units");
                });

            modelBuilder.Entity("VetFlow.Domain.Catalog.Unit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_units");

                    b.ToTable("units");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1000000-0000-4000-8000-000000000001"),
                            Name = "قطعة"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-4000-8000-000000000002"),
                            Name = "علبة"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-4000-8000-000000000003"),
                            Name = "كرتونة"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-4000-8000-000000000004"),
                            Name = "شريط"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-4000-8000-000000000005"),
                            Name = "قرص"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-4000-8000-000000000006"),
                            Name = "زجاجة"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-4000-8000-000000000007"),
                            Name = "سم"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-4000-8000-000000000008"),
                            Name = "مل"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-4000-8000-000000000009"),
                            Name = "لتر"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-4000-8000-000000000010"),
                            Name = "جرام"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-4000-8000-000000000011"),
                            Name = "كيلوجرام"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-4000-8000-000000000012"),
                            Name = "شيكارة"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-4000-8000-000000000013"),
                            Name = "متر"
                        });
                });

            modelBuilder.Entity("VetFlow.Domain.Categories.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("SearchText")
                        .IsRequired()
                        .HasMaxLength(700)
                        .HasColumnType("character varying(700)")
                        .HasColumnName("search_text");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("SearchText")
                        .HasDatabaseName("ix_categories_search_text");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchText"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("SearchText"), new[] { "gin_trgm_ops" });

                    b.HasIndex(new[] { "SearchText" }, "ix_categories_name_unique")
                        .IsUnique()
                        .HasDatabaseName("ix_categories_name_unique");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("VetFlow.Domain.Catalog.Product", b =>
                {
                    b.HasOne("VetFlow.Domain.Categories.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_products_categories_category_id");

                    b.HasOne("VetFlow.Domain.Catalog.Unit", null)
                        .WithMany()
                        .HasForeignKey("DefaultPurchaseUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_products_units_default_purchase_unit_id");

                    b.HasOne("VetFlow.Domain.Catalog.Unit", null)
                        .WithMany()
                        .HasForeignKey("DefaultSaleUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_products_units_default_sale_unit_id");

                    b.HasOne("VetFlow.Domain.Catalog.Manufacturer", null)
                        .WithMany()
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_products_manufacturers_manufacturer_id");

                    b.HasOne("VetFlow.Domain.Catalog.ProductNature", null)
                        .WithMany()
                        .HasForeignKey("NatureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_products_product_natures_nature_id");

                    b.HasOne("VetFlow.Domain.Catalog.Unit", null)
                        .WithMany()
                        .HasForeignKey("StorageUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_products_units_storage_unit_id");
                });

            modelBuilder.Entity("VetFlow.Domain.Catalog.ProductUnit", b =>
                {
                    b.HasOne("VetFlow.Domain.Catalog.Product", null)
                        .WithMany("Units")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_units_products_product_id");

                    b.HasOne("VetFlow.Domain.Catalog.Unit", null)
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_product_units_units_unit_id");
                });

            modelBuilder.Entity("VetFlow.Domain.Catalog.Product", b =>
                {
                    b.Navigation("Units");
                });
#pragma warning restore 612, 618
        }
    }
}
