using VetFlow.Application.Common;

namespace VetFlow.Application.Catalog.Commands.CreateProduct;

/// <summary>
/// Create a product (screen S3, WF-CAT-001, REQ-CAT-001): the mandatory minimum
/// (BR-CAT-009 / REQ-CAT-043), the identity and capability choices, the unit
/// profile (DEC-CAT-007/020), optional manual selling prices (BR-CAT-025), and
/// optional internal notes (BR-CAT-050). The internal code (DEC-CAT-026) is
/// generated by the system at persist time and is never supplied here.
/// The possible-duplicate warning (DEC-CAT-027) never blocks the write and is a
/// separate advisory read (BR-CAT-042 / DEC-CAT-018).
/// </summary>
public sealed record CreateProductCommand : ICommand<CreateProductResult>
{
    public required string ArabicName { get; init; }

    public string? EnglishName { get; init; }

    public string? Size { get; init; }

    public string? Concentration { get; init; }

    public required Guid CategoryId { get; init; }

    public required Guid ManufacturerId { get; init; }

    public required Guid NatureId { get; init; }

    public bool IsSplittable { get; init; }

    public bool IsRefrigerated { get; init; }

    public bool HasExpiration { get; init; }

    public bool HasOpenExpiration { get; init; }

    /// <summary>Mandatory only when <see cref="HasOpenExpiration"/> (BR-CAT-036, AC-CAT-031).</summary>
    public int? OpenExpirationPeriodDays { get; init; }

    public string? InternalNotes { get; init; }

    public required IReadOnlyList<CreateProductUnitInput> Units { get; init; }

    public required Guid StorageUnitId { get; init; }

    public required Guid DefaultSaleUnitId { get; init; }

    public required Guid DefaultPurchaseUnitId { get; init; }
}

/// <summary>One row of the unit profile in a create request (BR-CAT-016).</summary>
public sealed record CreateProductUnitInput
{
    public required Guid UnitId { get; init; }

    public required int Position { get; init; }

    /// <summary>User-entered conversion factor to the next unit; null on the smallest unit (BR-CAT-018).</summary>
    public decimal? QuantityInNextUnit { get; init; }

    public bool IsPurchaseUnit { get; init; }

    public bool IsSaleUnit { get; init; }

    public string? Barcode { get; init; }

    /// <summary>Independent manual selling price; sale units only (BR-CAT-025).</summary>
    public decimal? SellingPrice { get; init; }
}
